### ISSUE TITLE
crash with gtnh Botania     (Need your help)

### ISSUE THREAD

**Issue by mcmso** [AirBurn0/am2playground#1]
Botania in gtnh has made some changes, could you please make them compatible? I have also installed am2.5 in gtnh, and I really hope to use them in it
crash:
https://paste.ubuntu.com/p/qhxxYycg6y/
[crash-2023-09-01_21.03.52-client.txt](https://github.com/AirBurn0/am2playground/files/12498255/crash-2023-09-01_21.03.52-client.txt)

https://github.com/GTNewHorizons/Botania

About the integration :
If you're interested, try doing some  integration  with reika's ChromatiCraft

-----------------------------------------------------------
If you don't mind, can you tell me why it's not compatible with Alfheim

**Comment by AirBurn0** [comment]
**GTNH compat**
Oh, my bad. I tested my addon on original mods so I missed this. Well, at least it was fast to fix (tested with Botania-1.9.24-GTNH, along with aether and blood magic ones)
Is [this](https://github.com/AirBurn0/am2playground/releases/tag/0.11.0-hotfix1) works for you?

**Integration suggestion**
As I noted earlier, I simply do not know some mods (I am aware of the existence of ChromatiCraft, but I am very VERY bad at it, so without a month of playing with it on the modded server, it's unlikely to have integration soon). But okay then, maybe i will look for it.

**Comment by mcmso** [comment]
Successfully started after updating to hotfix version

**Comment by AirBurn0** [comment]
Considered fixed

**Comment by mcmso** [comment]
> 视为固定

![image](https://github.com/AirBurn0/am2playground/assets/46519955/afc89145-19c5-45e5-b593-d45955838f80)

**Comment by mcmso** [comment]
![image](https://github.com/AirBurn0/am2playground/assets/46519955/f41d604c-3da9-40e8-9313-8d9633364be6)

**Comment by GedeonGrays** [comment]
> If you don't mind, can you tell me why it's not compatible with Alfheim
I'd also like to know what the reason for the incompatibility is and why it wasn't reported to the Alfheim development team, and they just left it as is.

**Comment by AirBurn0** [comment]
> I'd also like to know what the reason for the incompatibility with Alfheim is and why it wasn't reported to the Alfheim developers, but instead just left it as is.

Cuz the problem is not with Alfheim, but rather with my **skill issue** for now.
Someday I maybe look to it actually be compatable, with some suggested integration items, along with botania ones, but for now it's just not and I'm leaving it be like this. 
However, for me it never was a good idea to make some modpacks with Alfheim and AM2 (becouse am2 simply ruins almost everything, tbh, and I suppose addon can make situation even worse), so I'm in no rush to fix it.
