### ISSUE TITLE
Wand Focus: Spell not craftable

### ISSUE THREAD

**Issue by ChaoticLaughter** [AirBurn0/am2playground#10]
<img width="404" alt="image" src="https://github.com/AirBurn0/am2playground/assets/49538589/f80fae29-05c0-48c3-b9a2-9ba819b3b24f">

<img width="460" alt="image" src="https://github.com/AirBurn0/am2playground/assets/49538589/70a28912-65c9-4c26-9f09-c6758baf6346">

I've been trying to make this item and it's not activating when I use the wand on the Runic matrix like it should, I got the 3 high essence cores, the warded glass, and the block of blue topaz, I also have all the essentia needed as well.

**Comment by AirBurn0** [comment]
Can't figure out why this happens, cuz I can craft it, after fully researching thaumonomicon entries.
Can you craft Ring of World Affection as well?
Did you research all the stuff??

**Comment by ChaoticLaughter** [comment]
Yeah I researched it, that's why I have the thaumonomicon entry

**Comment by AirBurn0** [comment]
> Yeah I researched it, that's why I have the thaumonomicon entry, so far I have everything I can researched, which are the spell components and the wand focus, dunno the pre-req researches/scans for the other stuff

oh god, I found where things got messed up.
My own code states that the Warp Amulet only need to be researched, which is incorrect.
Thanks for finding out, I'll fix that asap.

**Comment by AirBurn0** [comment]
[new version fixes this](https://github.com/AirBurn0/am2playground/releases/tag/v0.11.2)
