### ISSUE TITLE
incompatible am2.playerextensions.ExtendedProperties.getContingencyType

### ISSUE THREAD

**Issue by mcmso** [AirBurn0/am2playground#11]
https://github.com/Mithion/ArsMagica2/blob/6d6b68002363b2569c2f2300c8f9146ad800bbc6/src/main/java/am2/playerextensions/ExtendedProperties.java#L232
https://github.com/TCLProject/ArsMagica2-5/blob/796c0cc35999ffe0794e54fc20af337ea78ab0f8/src/main/java/am2/playerextensions/ExtendedProperties.java#L273

https://paste.ubuntu.com/p/MYB9cqFGxJ/

**Comment by AirBurn0** [comment]
Does it says something like 
![image](https://github.com/AirBurn0/am2playground/assets/69804577/89b7c8d4-dd36-41ca-80f6-426a6126b388)
this during the start?
There is a code that detects TCL fork and if so tries to search and invoke other methods via reflection api, 
but feels like it hasn't detected am2 correctly

**Comment by mcmso** [comment]
> Does logs says something like ![image](https://user-images.githubusercontent.com/69804577/281661319-89b7c8d4-dd36-41ca-80f6-426a6126b388.png) this during the start? There is a code that detects TCL fork and if so tries to search and invoke other methods via reflection api, but feels like it hasn't detected am2 correctly

[latest.log](https://github.com/AirBurn0/am2playground/files/13305983/latest.log)

**Comment by AirBurn0** [comment]
there are too many outputs, which is why the “earlier” logs were erased, so I can't see the line I need.
Please provide some "fresh" logs wich contains something like that ![image](https://github.com/AirBurn0/am2playground/assets/69804577/89b7c8d4-dd36-41ca-80f6-426a6126b388)

**Comment by mcmso** [comment]
Well I circumvented this for now with some config

**Comment by mcmso** [comment]
> there are too many outputs, which is why the “earlier” logs were erased, so I can't see the line I need. Please provide some "fresh" logs wich contains something like that ![image](https://user-images.githubusercontent.com/69804577/281661319-89b7c8d4-dd36-41ca-80f6-426a6126b388.png) btw this looks sus, ![image](https://user-images.githubusercontent.com/69804577/281677860-84533866-966d-4f56-a57e-141995ba4c29.png) and means that am2pg can't really look up for TCL fork

But I'm sorry I can't find a similar sentence

**Comment by AirBurn0** [comment]
> > there are too many outputs, which is why the “earlier” logs were erased, so I can't see the line I need. Please provide some "fresh" logs wich contains something like that ![image](https://user-images.githubusercontent.com/69804577/281661319-89b7c8d4-dd36-41ca-80f6-426a6126b388.png) btw this looks sus, ![image](https://user-images.githubusercontent.com/69804577/281677860-84533866-966d-4f56-a57e-141995ba4c29.png) and means that am2pg can't really look up for TCL fork
> 
> But I'm sorry I can't find a similar sentence

try to kinda launch it and then close in init phase, so logs wont get junked.
![image](https://github.com/AirBurn0/am2playground/assets/69804577/9f7c3d27-f970-499b-80e4-9f155f24bcfa)

> Well I circumvented this for now with some config

Maybe I should really create some config to force that...

**Comment by AirBurn0** [comment]
Okay I totally [made](https://github.com/AirBurn0/am2playground/releases/tag/v0.11.2-dev1) myself adjust some config, and now you can force compatibility with some known am2 forks, just like so:
![image](https://github.com/AirBurn0/am2playground/assets/69804577/b1b087fc-1c1b-47d1-9419-30317310faf9)

**Comment by mcmso** [comment]
> Okay I totally [made](https://github.com/AirBurn0/am2playground/releases/tag/v0.11.2-dev1) myself adjust some config, and now you can force compatibility with some known am2 forks, just like so: ![image](https://user-images.githubusercontent.com/69804577/282069368-6fe3413d-89c8-4860-9dfb-d85c88f4cf4a.png)
> 
> This is still unnecessary if it auto-detects correctly

Thank you very much for your help
There has been no recurrence of such problems
