### ISSUE TITLE
Incompatibility with Baubles Expanded

### ISSUE THREAD

**Issue by Milii20** [AirBurn0/am2playground#19]
Hello!, as the title says, even tho Baubles Expanded seems to be compatible with any other old baubles mod, if AM2Playground has the Baubles's compat enabled it crashes when you swap the old Baubles with Baubles Expanded. The game runs fine with the bauble's compat disabled.

Here is the crash report: https://pastebin.com/yb2HYgSV

Here is the link to Baubles Expanded: https://modrinth.com/mod/baubles-expanded and it's opensource, here is the code in case it helps: https://github.com/jss2a98aj/Baubles-Expanded

Anything else i can help please tell me.
Thank you very much!

**Comment by AirBurn0** [comment]
I was never intended to make AM2PG compatible with Baubles Expanded, because I didn't know about its existence.
I'll see if it's possible to make them compatible.

**Comment by AirBurn0** [comment]
> Here is the crash report: https://pastebin.com/yb2HYgSV

Problem was: azanor's baubles adding Miner's ring, but jss2a98aj's one doesn't, that's why it breaks.

Well, in general, a miner's ring in crafting is not very fair, okay. I'll replace it with a gold bar, in general, I think it's ok.

Now I’m sprinting around with this all sorts of  Aethers and other such mods to make sure that at least for those mods that I know about it works well.

**Comment by AirBurn0** [comment]
To be honest, I didn’t really find (didn't try very hard) any mods for which Baubles Expanded would be necessary at all, so it's difficult for me to fully test my solution "in a battle".
Sorry for answering so late, I procrastinated.
Please report back if it works and any other bugs you may find.

**Comment by Milii20** [comment]
Hello again! and again thank you very much!, it's definitly not late
The only mods i found that use baubles expanded so far (there has to be more), are et futurum requiem (which adds a slot for elytra) and cutting edge (which adds a slot for an auto portable minecart, pretty useful), but the ability to have extra baubles's slots is kinda interesting in this version
Everything seems to be in working order, and again, thank you very much for the quick update!

**Comment by brandyyn** [comment]
> Hello again! and again thank you very much!, it's definitly not late The only mods i found that use baubles expanded so far (there has to be more), are et futurum requiem (which adds a slot for elytra) and cutting edge (which adds a slot for an auto portable minecart, pretty useful), but the ability to have extra baubles's slots is kinda interesting in this version Everything seems to be in working order, and again, thank you very much for the quick update!

there is also https://github.com/creditcrab-mods/BaubleTweaks

and aether legacy departure will be moved to baubles expanded

and gtnh is taking on baubles expanded and will add more equipment soon, including a full replacement of travellers gear using it
