### ISSUE TITLE
GTNH TC-Wands compat(Need your help) 

### ISSUE THREAD

**Issue by mcmso** [AirBurn0/am2playground#2]
https://github.com/AirBurn0/am2playground/issues/1#issuecomment-1702803827
https://github.com/KuroPeach/GTNH-TC-Wands
https://github.com/GTNewHorizons/GTNH-TC-Wands

**Comment by AirBurn0** [comment]
> mcmso

okay, [done](https://github.com/AirBurn0/am2playground/releases/tag/v0.11.1-test)
![image](https://github.com/AirBurn0/am2playground/assets/69804577/de9b28f9-24c8-4636-bbb3-2a289cf251fb)

Is it works for you?
It took me so long because i researched what it actually is and almost burned my computer im process, btw...

**Comment by AirBurn0** [comment]
Btw, how do you EVEN manage to craft this without using ThaumicTinkererKami or Automagy??????
![image](https://github.com/AirBurn0/am2playground/assets/69804577/7f3f3e17-3e52-4276-9096-8c45810328de)

**Comment by mcmso** [comment]
> Is it works for you? It took me so long because I researched what it actually is and almost burned my computer in process...

Ah, I mean gtnh tc disables the normal wand synthesis method, just requires you to add a recipe that can be synthesized normally, not limited to this hardcore recipe

**Comment by mcmso** [comment]
If possible, do you have discord to make it easier for people to connect with you

**Comment by mcmso** [comment]
> Btw, [GTNH-TC-Wands](https://github.com/KuroPeach/GTNH-TC-Wands) seems really BROKEN BALANCE for me, cuz how do you EVEN manage to craft this without using ThaumicTinkererKami or Automagy?????? I spent 2 hours trying and didn't get it...

gtnh's tc wand needs to be progressively upgraded to advanced materials,
And then we'll go back and find the best part combination to match the best tcwand,
Like magic reduction like vis capacity

**Comment by AirBurn0** [comment]
> > Is it works for you? It took me so long because I researched what it actually is and almost burned my computer in process...
> 
> Ah, I mean gtnh tc disables the normal wand synthesis method, just requires you to add a recipe that can be synthesized normally, not limited to this hardcore recipe


If it works, then I consider **suggestion complete**.



> If possible, do you have discord to make it easier for people to connect with you

I planned to create a discord channel as soon as the mod becomes a **little more popular**. So, maybe soon(tm)...

**Comment by mcmso** [comment]
> > > Is it works for you? It took me so long because I researched what it actually is and almost burned my computer in process...
> > 
> > 
> > Ah, I mean gtnh tc disables the normal wand synthesis method, just requires you to add a recipe that can be synthesized normally, not limited to this hardcore recipe
> 
> If it works, then I consider **suggestion complete**.
> 
> > If possible, do you have discord to make it easier for people to connect with you
> 
> I planned to create a discord channel as soon as the mod becomes a **little more popular**. So, maybe soon(tm)...

I'm sorry I don't have time to test its stability until now
I had a crash here during the launch of minecraft
[crash-2023-09-05_23.26.50-client.txt](https://github.com/AirBurn0/am2playground/files/12525501/crash-2023-09-05_23.26.50-client.txt)
[latest.log](https://github.com/AirBurn0/am2playground/files/12525504/latest.log)
https://paste.ubuntu.com/p/xmHVztF8sC/

**Comment by AirBurn0** [comment]
> > Crashlog says something went wrong during run of those mods: gregtech{MC1710} miscutils{1.9.85} ForgeMicroblock{1.3.4} GalaxySpace{1.2.7-GTNH} ToxicEverglades{1.9.85}
> > Is it works without addon? With previous version? I can't figure the problem by now
> 
> Use # #1 1hotfix version of the version does not have any problems and run perfect

maybe I messed up registration, or maybe not
try [this](https://github.com/AirBurn0/am2playground/releases/tag/idk) versions

**Comment by mcmso** [comment]
All three versions worked well in my tests
And tcwand recipe can also be used normally, you're very reliable


maybe1:
[latest.log](https://github.com/AirBurn0/am2playground/files/12531886/latest.log)

maybe2:
[latest.log](https://github.com/AirBurn0/am2playground/files/12531747/latest.log)

maybe3:
[latest.log](https://github.com/AirBurn0/am2playground/files/12531711/latest.log)
