### ISSUE TITLE
Crash in Multiplayer (maybe related to using new java)

### ISSUE THREAD

**Issue by Milii20** [AirBurn0/am2playground#20]
Hello again!, Sorry to keep on bothering, but since i found another but i wanted to report it

Here is the crash report: https://pastebin.com/8ZEPTLhv

In this case, i added ArsMagica2 1.6.7 and am2playground to a.. pretty much GTNH server instance with java 17.
I used the AM2PlayGround-Beta-0.11.4-beta1-do_not_distrib version which works on new java clients, but not in servers

Thank you very much again for your time!

**Comment by AirBurn0** [comment]
> Hello again!, Sorry to keep on bothering, but since i found another but i wanted to report it
> 
> Here is the crash report: https://pastebin.com/8ZEPTLhv
> 
> In this case, i added ArsMagica2 1.6.7 and am2playground to a.. pretty much GTNH server instance with java 17. I used the AM2PlayGround-Beta-0.11.4-beta1-do_not_distrib version which works on new java clients, but not in servers
> 
> Thank you very much again for your time!

AM2PlayGround-Beta-0.11.4-beta1-do_not_distrib is not for public use... But yeah, since I would most likely forget to test this on the server before release, thanks for the reminder.

**Comment by AirBurn0** [comment]
[This](https://github.com/AirBurn0/am2playground/releases/tag/v0.11.4-beta2) should do.
Please consider continuing to test beta versions of my addon so that I can make unfucked release this time.

**Comment by Milii20** [comment]
Hello!, Thank you for the quick update, seems to work perfectly!, i will report anything wrong i can find but for the time being, seems really stable, Thank you very much!
