### ISSUE TITLE
AM2Playground trying to load more client stuff in the server

### ISSUE THREAD

**Issue by Milii20** [AirBurn0/am2playground#21]
Hello! since i said i would report again if this happened again, here i go!, same huge modpack, went into another dimension, server crashed, restarted, and was able to login perfectly, only have this crash report, will add more info as soon as i get more

Here is the crash report: https://pastebin.com/TaXyD0Ci

Thank you very much for your time!

EDIT: and here we have anotherone! https://pastebin.com/HHniMsDz
seems to be consistent, dungeon structure when generating loot calling client function

**Comment by AirBurn0** [comment]
> Hello! since i said i would report again if this happened again, here i go!, same huge modpack, went into another dimension, server crashed, restarted, and was able to login perfectly, only have this crash report, will add more info as soon as i get more
> 
> Here is the crash report: https://pastebin.com/TaXyD0Ci
> 
> Thank you very much for your time!
> 
> EDIT: and here we have anotherone! https://pastebin.com/HHniMsDz seems to be consistent, dungeon structure when generating loot calling client function

I'm aware of this for about 3 days now, but I still haven’t fixing it yet.
I'll let you know as soon as I fix it.

**Comment by AirBurn0** [comment]
[That](https://github.com/AirBurn0/am2playground/releases/tag/v0.11.4-beta3) should do
@Milii20 feel free to continue your tests

**Comment by Milii20** [comment]
Hello!, again, thank you for the quick update!, it seems to work perfectly!
Will report new findings, don't worry, but for the most part, seems to be all good now
