### ISSUE TITLE
LoTRmod integration

### ISSUE THREAD

**Issue by phD-Smth** [AirBurn0/am2playground#4]
I have a small modpack with both Lord of the Rings Mod and Ars Magica 2 and was long thinking of a certain tiny integration:

In LotR Mod there's two places that deal "environmental damage" periodically - in the north, in Forodwaith, you take cold damage unless wearing fur armor, and in the south, in Harad desert, during the day you take heat damage unless wearing bedouin/nomad armor. 

In Ars Magica, there's elemental affinity, so it would be cool to get immunity to the desert with a certain fire affinity, and to the frost with ice affinity.

Careful - in LotR Mod, biomes are not implemented with vanilla system

**Comment by AirBurn0** [comment]
типа [такого](https://github.com/AirBurn0/am2playground/releases/tag/v0.11.1-lotr)?

**Comment by phD-Smth** [comment]
В фородвайте всё ещё получаю урон при ледяном аффинити
В хараде при огненном вроде нет
А как в этом аддоне и/или Арсмагике 2.5 посмотреть своё аффинити? Вроде помню, что в окулусе раньше была вкладка, но сейчас она не появляется

**Comment by AirBurn0** [comment]
> В фородвайте всё ещё получаю урон при ледяном аффинити

а оу

> Арсмагике 2.5 посмотреть своё аффинити? Вроде помню, что в окулусе раньше была вкладка, но сейчас она не появляется

там с этим какой-то баг, надо /setmagiclevel потеребонить

**Comment by AirBurn0** [comment]
> В фородвайте всё ещё получаю урон при ледяном аффинити В хараде при огненном вроде нет

# TL;DR
Вообще оно как работает:
Каждые 20 тиков (секунду), активируется событие,
Для Фородвайта, он имеется базовое значение 50, и добавляется +100 за каждый элемент меховой брони (или +50 за кожанную)
Если в измерении идет дождь - значение делится на 3, и если игрок в моде - то на 20.
Ну и потом берется случайное число от 0 до этого значения, и если выпадает 0 - то тебя и бьет.
Так что условный базовый шанс получить обморожение это 1/50, если ты в дождь решил поплавать - 1/1, при полной экипировке 1/450.
Событие, конечно, зависит от освещения и прямой видимости неба, но на шансы это не влияет (он просто не сработает никогда если игрок условно в пещере и не плавает).

Так как Affinity можно догнать до 100% за где-то полчаса (от версии AM2 зависит? но не суть), я сделал следующую модификацию:
К значению события добавляется округленная вниз до целых 1000 * (%родства)<sup>2</sup>. (после обсчета модификаторов воды и дождя, потому что я могу)
Так что условно с 50% родства с льдом, даже искупавшись в дождь на поверхности, можно остаться с 50/3/20 + 1000*0.5*0.5 = (после всех целочисленных округлений) 250, а значит шанс словить обморожение будет 1/250 (как в полном кожаном сете, ну или двумя частями меховой), что как по мне хотя-бы немного балансно...
при 100% там вообще втупую 2147483647 возвращается, так что шансов на то что тебя при таком раскладе продамажит практически никаких...
Харад я делал по аналогии, только там нет модификаторов дождя и воды.
# ДА
Ты как тестил это дело вообще? /setaffinity ICE 100 собственно делает ровно то, что и должно - нивелирует шансы продамажиться (только что перепроверял).

**Comment by phD-Smth** [comment]
Ну вроде работает тогда

Ещё можно ради прикола добавить такой конфиг, чтобы холодное аффинити увеличивало урон на юге, а горячее - на севере

**Comment by AirBurn0** [comment]
> Ещё можно ради прикола добавить такой конфиг, чтобы холодное аффинити увеличивало урон на юге, а горячее - на севере

увеличивало урон в плане как?
от спеллов, от типа урона, добавляло скажем Fire Damage как некоторые вещи в моем аддоне, или еще как-нибудь..?
Это все слишком разные механики чтобы решить этот вопрос с наскока

**Comment by AirBurn0** [comment]
Прикрою Issue до поры до времени т.к. все описанные фичи я уже сделал (ну кроме увеличения урона, т.к. требуется куда более сильно проработанная механика)
