### ISSUE TITLE
Server crashes after installing AM2PlayGround

### ISSUE THREAD

**Issue by gengyunmaster** [AirBurn0/am2playground#5]
Hello! It seems that AM2PG calls a class that is client-only which causes the server to crash during initialization. Client can work properly, but server can not. Looking forward to a fix in the upcoming version of AM2PG. Thank you for your help!
[crash-2023-09-17_20.40.54-server.txt](https://github.com/AirBurn0/am2playground/files/12642869/crash-2023-09-17_20.40.54-server.txt)

**Comment by AirBurn0** [comment]
Okay, [here you go](https://github.com/AirBurn0/am2playground/releases/tag/v0.11.1-hotfix1). Is it working correct?

**Comment by gengyunmaster** [comment]
Great! This version works correctly with both client and server. Thank you very much!!!
BTW, your mod is very interesting!

**Comment by AirBurn0** [comment]
> Great! This version works correctly with both client and server. Thank you very much!!! BTW, your mod is very interesting!

10Q, considered solved.
