### ISSUE TITLE
Client crashes with unexpected error

### ISSUE THREAD

**Issue by gengyunmaster** [AirBurn0/am2playground#6]
[crash-2023-09-21_19.17.09-client.txt](https://github.com/AirBurn0/am2playground/files/12684198/crash-2023-09-21_19.17.09-client.txt)
[crash-2023-09-21_19.32.56-client.txt](https://github.com/AirBurn0/am2playground/files/12684203/crash-2023-09-21_19.32.56-client.txt)

**Comment by AirBurn0** [comment]
> [crash-2023-09-21_19.17.09-client.txt](https://github.com/AirBurn0/am2playground/files/12684198/crash-2023-09-21_19.17.09-client.txt) [crash-2023-09-21_19.32.56-client.txt](https://github.com/AirBurn0/am2playground/files/12684203/crash-2023-09-21_19.32.56-client.txt)

Can you reproduce bug using [this](https://github.com/AirBurn0/am2playground/releases/tag/v0.11.1-test1)? I'm kinda suspect what can go wrong but I want to be sure

**Comment by gengyunmaster** [comment]
The new version (0.11.1-hotfix2) of AM2PG has been installed to reproduce the crash. Here is the crash report. Thank you!
[crash-2023-09-22_14.06.28-client.txt](https://github.com/AirBurn0/am2playground/files/12697386/crash-2023-09-22_14.06.28-client.txt)

**Comment by AirBurn0** [comment]
> The new version (0.11.1-hotfix2) of AM2PG has been installed to reproduce the crash. Here is the crash report. Thank you! [crash-2023-09-22_14.06.28-client.txt](https://github.com/AirBurn0/am2playground/files/12697386/crash-2023-09-22_14.06.28-client.txt)

Can you also provide .log file? There is some additional info that i wanted to see.

**Comment by gengyunmaster** [comment]
OK. Here is the log. What's more, I would like to provide more information related to this strange crash. My friend and I are playing a modpack handling on a server. We have not done anything related to AM2PG yet, but my client crashed suddenly. After that, once I restart my game and join the server, my game will crash. However, my friend can play in the server normally. If he go to the location where I encountered the crash and do similar things as I did, his game will not crash. It's really unintelligible!
[latest.log](https://github.com/AirBurn0/am2playground/files/12699824/latest.log)

**Comment by AirBurn0** [comment]
> OK. Here is the log. What's more, I would like to provide more information related to this strange crash. My friend and I are playing a modpack handling on a server. We have not done anything related to AM2PG yet, but my client crashed suddenly. After that, once I restart my game and join the server, my game will crash. However, my friend can play in the server normally. If he go to the location where I encountered the crash and do similar things as I did, his game will not crash. It's really unintelligible! [latest.log](https://github.com/AirBurn0/am2playground/files/12699824/latest.log)

[Gotcha](https://github.com/AirBurn0/am2playground/releases/tag/v0.11.1-hotfix2), thanks for finding out!

**Comment by gengyunmaster** [comment]
Woooooo! This version works fine. The issue has been fixed. Thank you very much!

**Comment by AirBurn0** [comment]
yea
