### ISSUE TITLE
Sunstone alloy and Moonlight hide uncraftable?

### ISSUE THREAD

**Issue by ChaoticLaughter** [AirBurn0/am2playground#9]
I can't seem to make either sunstone alloy or moonlight hide, I've been using gold, sunstone, and Purified vinteum dust in the essence refiner and I can't seem to make it regardless of what order I put any of the items in, similarly I tried this with Moonstone, Leather, and purified/arcane ash.

**Comment by ChaoticLaughter** [comment]
Oh, the book didn't even show the recipes in the first place that would explain a lot

**Comment by AirBurn0** [comment]
> Oh, the book didn't even show the recipes in the first place that would explain a lot

AM2 sourcecode dealing with it like so:
is it essence or deficit crystal? no? no recipe then.

btw implemented some code to surpass the restrictions, check the book in next upd.

**Comment by AirBurn0** [comment]
[new version fixes this](https://github.com/AirBurn0/am2playground/releases/tag/v0.11.2)
